//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FPExam.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counter
    {
        public short ID { get; set; }
        public Nullable<int> Counter1 { get; set; }
    }
}
